server:
  port: 7800
  tomcat.uri-encoding: utf-8

spring:
  application:
    name: rm-tcc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr:

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata-demo
  service:
    vgroup-mapping:
      seata-demo: guangzhou
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr:
      namespace: 8f11aeb1-5042-461b-b88b-d47a7f7e01c0
      group: DEFAULT_GROUP