server:
  port: 7800
  tomcat.uri-encoding: utf-8

spring:
  application:
    name: service-tcc1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #远程数据库链接
    url: jdbc:mysql://127.0.0.1/seata_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr:
        namespace:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      #需要和server在同一个注册中心下
      serverAddr:
      namespace:
      #需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr:
      namespace:
      group: SEATA_GROUP
